import React, { useState, useEffect, useCallback } from "react";

interface Question {
  question: string;
  options: string[];
  answer: string;
}

const questions: Question[] = [
  {
    question: "Which of the following is the use of function in Python?",
    options: ["Functions don’t provide better modularity", "You can't also create your own functions", "Functions are reusable pieces of programs", "All of the mentioned"],
    answer: "Functions are reusable pieces of programs",
  },
  {
    question: "What is the output of the following?\nx = 'abcd'\nfor i in range(x):\n  print(i)",
    options: ["a b c d", "error", "0 123", "none of the mentioned"],
    answer: "error",
  },
  {
    question: "What will be the output of the following Python code?\nmin(max(False, -3, -4), 2, 7)",
    options: ["-4", "False", "-3", "2"],
    answer: "False",
  },
  {
    question: "Which of the following numbers can never be generated by the following code?\nrandom.randrange(0, 50)",
    options: ["0", "1", "49", "50"],
    answer: "50",
  },
  {
    question: "Which of the following items are present in the function header?",
    options: ["parameter list", "Both (A) and B", "return value", "function name"],
    answer: "Both (A) and B",
  },
  {
    question: "Which of the following file can be opened in any text editor?",
    options: ["text", "None of the above", "Binary", "Both of the above"],
    answer: "text",
  },
  {
    question: "What is the output of the following code?\ny = \"I love Python\"\ny(3) = 's'\nprint(y)",
    options: ["Error", "snow world", "snos world", "snow"],
    answer: "Error",
  },
  {
    question: "In which data type is indexing not valid?",
    options: ["list", "dictionary", "string", "none of the above"],
    answer: "none of the above",
  },
  {
    question: "What will the following code segment print?\na = True\nb = False\nc = False\nif a or b and c:\n  print(\"HELLO\")\nelse:\n  print(\"hello\")",
    options: ["Hello", "HELLO", "None of these", "hello"],
    answer: "HELLO",
  },
  {
    question: "What is the output of the following?\nt = (2, 3, 4, 3.5, 5, 6)\nprint(sum(t) + t.count(2))",
    options: ["24.5", "25.5", "23.5", "24"],
    answer: "25.5",
  },
  {
    question: "What is the output of the following code?\na = 50\nb = a = a * 5\nprint(b)",
    options: ["Syntax Error", "250", "10", "50"],
    answer: "250",
  },
  {
    question: "What will be the output of the following Python code?\ndef sayHello():\n  print(\"Hello World!\")\nsayHello()\nsayHello()",
    options: ["Hello Hello", "Hello World! Hello World!", "None of the above", "Hello World! Hello World!"],
    answer: "Hello World! Hello World!",
  },
  {
    question: "Identify the correct function header.",
    options: ["def fun(a, b=2, c=3)", "def fun(a=2, b, c=3)", "def fun(a=2, b=3, c)", "def fun(a, b, c=3, d)"],
    answer: "def fun(a, b=2, c=3)",
  },
  {
    question: "Which one of the following is correct?",
    options: ["Dictionary can neither have same keys nor same values", "Dictionary can have two same keys with different values", "Dictionary can have two same keys but cannot have same pair", "Dictionary can have two same values with different keys"],
    answer: "Dictionary can have two same values with different keys",
  },
  {
    question: "Which keyword is used for function?",
    options: ["function", "def", "define", "fun"],
    answer: "def",
  },
  {
    question: "Which module in Python is used for mathematical operations on large arrays and matrices?",
    options: ["numpy", "pandas", "math", "none of these"],
    answer: "numpy",
  },
  {
    question: "NumPY stands for?",
    options: ["Number in Python", "Numerical Python", "Numbering Python", "None of these"],
    answer: "Numerical Python",
  },
  {
    question: "What will be the output of print(\"%.2f\" % 56.236)?",
    options: ["56.236", "56.0000", "56.23", "56.24"],
    answer: "56.23",
  },
  {
    question: "Which mode returns the typed statement to the result instantly?",
    options: ["Functional", "Interactive", "Script", "Object-oriented"],
    answer: "Interactive",
  },
  {
    question: "What are the three steps for algorithm construction?",
    options: ["Sequence Selection Repetition", "Input Output Process", "Input Output Decision Repetition", "None of these"],
    answer: "Sequence Selection Repetition",
  },
  {
    question: "Which of the following is an invalid mode?",
    options: ["w", "r+", "a", "ar+"],
    answer: "ar+",
  },
  {
    question: "What is the default type of numpy?",
    options: ["float64", "float32", "int64", "int32"],
    answer: "float64",
  },
  {
    question: "Which function is used to delete a file entirely in Python?",
    options: ["clear()", "delete()", "erase()", "remove()"],
    answer: "remove()",
  },
  {
    question: "The actual instructions in flowcharting are shown in ________",
    options: ["Arrows", "Circles", "Lines", "Boxes"],
    answer: "Boxes",
  },
  {
    question: "What is an algorithm?",
    options: ["a decision", "a flow chart", "a flowchart or pseudocode", "Step-by-step instructions used to solve a problem"],
    answer: "Step-by-step instructions used to solve a problem",
  },
  {
    question: "ndarray refers to?",
    options: ["Matrix", "List", "None of these", "Array"],
    answer: "Array",
  },
  {
    question: "Testing is known as?",
    options: ["Finding broken code", "None of the above", "A stage of all projects", "Evaluating deliverable to find errors"],
    answer: "Evaluating deliverable to find errors",
  },
  {
    question: "What is the output of the following?\nimport numpy as np\na = np.array([1, 2, 3])\nprint(a.shape)",
    options: ["(3,1)", "(1,3)", "(3,)", "(0,3)"],
    answer: "(3,)",
  },
  {
    question: "_______ is broadcasting in numpy?",
    options: ["Distribution", "Extension", "Broadcasting", "Propagation"],
    answer: "Broadcasting",
  },
  {
    question: "________ is a detailed flowchart?",
    options: ["union", "macro", "micro", "stack"],
    answer: "macro",
  },
  {
    question: "What is the output of:\nDay = (\"Sun\" \"Mon\" \"Tue\")\nprint(Day[-1])",
    options: ["Tue", "Sun", "None of these", "Mon"],
    answer: "None of these",
  },
  {
    question: "How many keywords are in Python (approx)?",
    options: ["35", "30", "33", "32"],
    answer: "35",
  },
  {
    question: "What is the output of 5 | 2, 5 // 2?",
    options: ["7, 2", "2.5", "5", "2"],
    answer: "7, 2",
  },
  {
    question: "Which is not a characteristic of high-level languages?",
    options: ["Interactive execution", "User friendly", "Platform Independent", "Machine code"],
    answer: "Machine code",
  },
  {
    question: "Which function does not necessarily accept only recursive calls?",
    options: ["map()", "lambda()", "reduce()", "filter()"],
    answer: "lambda()",
  },
  {
    question: "Any algorithm is a program?",
    options: ["May be", "Can't say", "False", "True"],
    answer: "False",
  },
  {
    question: "Which step does not come after algorithm creation?",
    options: ["Program testing", "Program debugging", "Program maintenance", "Program coding"],
    answer: "Program coding",
  },
  {
    question: "What is Lambda function in Python?",
    options: ["A one-line anonymous function", "A built-in Python function", "A private function", "None of the above"],
    answer: "A one-line anonymous function",
  },
  {
    question: "What is Type Casting in Programming?",
    options: ["Declaring variables", "Assigning values", "Converting one data type to another", "None of these"],
    answer: "Converting one data type to another",
  },
  {
    question: "Python is translated into machine code by?",
    options: ["Compiler", "Interpreter and compiler", "None of these", "Interpreter"],
    answer: "Interpreter",
  },
  {
    question: "Which function is built-in in Python?",
    options: ["factorial()", "print()", "seed()", "sqrt()"],
    answer: "print()",
  },
  {
    question: "Which data structure works on FIFO principle?",
    options: ["queue", "Stack", "Array", "Linked List"],
    answer: "queue",
  },
  {
    question: "What is pickling?",
    options: ["It is used for object serialization", "It is used for object deserialization", "Both", "None"],
    answer: "It is used for object serialization",
  },
  {
    question: "The algorithm process is used for?",
    options: ["Automated tasks", "Scripted", "Any", "Performed"],
    answer: "Automated",
  },
  {
    question: "Flow charts and algorithms are used for?",
    options: ["Better Programming", "Optimized Coding", "Systematic Testing", "All of the above"],
    answer: "All of the above",
  },
  {
    question: "Which data type is not used in programming?",
    options: ["char", "int", "float", "character"],
    answer: "character",
  },
  {
    question: "How can we convert Numpy array to list?",
    options: ["list(array)", "list.array", "array.list", "None"],
    answer: "list(array)",
  },
  {
    question: "N-dimensional array in NumPy is called?",
    options: ["narray", "nd_array", "ndarray", "darray"],
    answer: "ndarray",
  },
  {
    question: "Which data structure works on LIFO principle?",
    options: ["Stack", "Queue", "Array", "Linked List"],
    answer: "Stack",
  },
  {
    question: "Which is used in reverse order to reach the last element?",
    options: ["Stack", "Array", "Linked List", "Queue"],
    answer: "Stack",
  },
