import React, { useState, useEffect, useCallback } from "react";

interface Question {
  question: string;
  options: string[];
  answer: string;
}

const m3Questions: Question[] = [
  { question: "Who developed the Python programming language?", options: ["Guido van Rossum", "Dennis Ritchie", "James Gosling", "Bjarne Stroustrup"], answer: "Guido van Rossum" },
  { question: "Which of the following is the correct extension of the Python file?", options: [".python", ".pl", ".py", ".p"], answer: ".py" },
  { question: "Is Python case sensitive when dealing with identifiers?", options: ["Yes", "No", "Depends on OS", "None of the mentioned"], answer: "Yes" },
  { question: "Which of the following is not a keyword in Python?", options: ["eval", "assert", "nonlocal", "pass"], answer: "eval" },
  { question: "Which function is used to get the length of a list in Python?", options: ["count()", "length()", "len()", "size()"], answer: "len()" },
  { question: "What is the output of 'print(2**3)'?", options: ["6", "8", "9", "12"], answer: "8" },
  { question: "Which of the following is an immutable data type in Python?", options: ["List", "Dictionary", "Tuple", "Set"], answer: "Tuple" },
  { question: "How do you start a comment in Python?", options: ["//", "/*", "#", "--"], answer: "#" },
  { question: "What is the result of 'print(type(5.0))'?", options: ["<class 'int'>", "<class 'float'>", "<class 'number'>", "<class 'double'>"], answer: "<class 'float'>" },
  { question: "Which of the following is used to define a block of code in Python?", options: ["Brackets", "Indentation", "Parentheses", "Quotation marks"], answer: "Indentation" },
  { question: "What is the output of 'print(\"Hello\"[1])'?", options: ["H", "e", "l", "o"], answer: "e" },
  { question: "Which operator is used for floor division in Python?", options: ["/", "//", "%", "**"], answer: "//" },
  { question: "Which keyword is used for function declaration?", options: ["fun", "define", "def", "func"], answer: "def" },
  { question: "What is the value of 'print(10 % 3)'?", options: ["3", "1", "0", "10"], answer: "1" },
  { question: "Which of the following represents a dictionary in Python?", options: ["[]", "()", "{}", "<>"], answer: "{}" },
  { question: "What is the result of 'bool(0)' in Python?", options: ["True", "False", "None", "Error"], answer: "False" },
  { question: "Which method is used to add an element to the end of a list?", options: ["add()", "insert()", "append()", "push()"], answer: "append()" },
  { question: "What is the result of 'print(\"abc\".upper())'?", options: ["Abc", "abc", "ABC", "Error"], answer: "ABC" },
  { question: "Which function is used to take input from the user?", options: ["get()", "scan()", "input()", "read()"], answer: "input()" },
  { question: "What is the default return value of a function that does not return anything?", options: ["0", "False", "None", "Null"], answer: "None" },
  { question: "Which of the following is a NumPy array attribute that returns the number of dimensions?", options: ["ndim", "shape", "size", "dtype"], answer: "ndim" },
  { question: "What is the correct way to import NumPy?", options: ["import numpy", "import numpy as np", "from numpy import *", "All of the above"], answer: "import numpy as np" },
  { question: "Which of the following is used to create a NumPy array?", options: ["np.list()", "np.array()", "np.table()", "np.object()"], answer: "np.array()" },
  { question: "What is the output of 'print(range(5))' in Python 3?", options: ["[0, 1, 2, 3, 4]", "range(0, 5)", "0 1 2 3 4", "Error"], answer: "range(0, 5)" },
  { question: "Which of the following is a sequence data type?", options: ["Integer", "List", "Dictionary", "Float"], answer: "List" },
  { question: "What is the output of 'print(\"Python\" * 2)'?", options: ["PythonPython", "Python 2", "Python2", "Error"], answer: "PythonPython" },
  { question: "Which loop is used to iterate over a sequence?", options: ["while", "for", "do-while", "if"], answer: "for" },
  { question: "What is the use of 'break' statement?", options: ["To skip the current iteration", "To terminate the loop", "To restart the loop", "To handle exceptions"], answer: "To terminate the loop" },
  { question: "Which method is used to remove a specific element from a list?", options: ["delete()", "pop()", "remove()", "discard()"], answer: "remove()" },
  { question: "What is a 'lambda' function in Python?", options: ["A function with many names", "An anonymous single-line function", "A function used for plotting", "A function that never returns"], answer: "An anonymous single-line function" },
  { question: "Which of the following is used to handle exceptions in Python?", options: ["try...except", "try...catch", "do...while", "if...else"], answer: "try...except" },
  { question: "How do you open a file for reading in Python?", options: ["open(\"file.txt\", \"w\")", "open(\"file.txt\", \"r\")", "open(\"file.txt\", \"a\")", "open(\"file.txt\", \"x\")"], answer: "open(\"file.txt\", \"r\")" },
  { question: "What does 'pip' stand for?", options: ["Python Install Program", "Preferred Installer Program", "Python Intranet Program", "None of these"], answer: "Preferred Installer Program" },
  { question: "Which of the following is a built-in module in Python?", options: ["math", "random", "os", "All of the above"], answer: "All of the above" },
  { question: "What is the output of 'print(abs(-5))'?", options: ["-5", "5", "0", "None"], answer: "5" },
];
const questionsPart2: Question[] = [
  { question: "What is the result of '10 / 2' in Python 3?", options: ["5", "5.0", "2", "Error"], answer: "5.0" },
  { question: "Which of the following is not a bitwise operator?", options: ["&", "|", "^", "&&"], answer: "&&" },
  { question: "How do you check if a key exists in a dictionary?", options: ["key in dict", "dict.has(key)", "dict.exists(key)", "dict.contains(key)"], answer: "key in dict" },
  { question: "What is the output of 'print(3 < 2 or 5 > 4)'?", options: ["True", "False", "None", "Error"], answer: "True" },
  { question: "Which function converts a string to an integer?", options: ["str()", "float()", "int()", "chr()"], answer: "int()" },
  { question: "What is slicing used for in Python?", options: ["To delete elements", "To extract a portion of a sequence", "To sort a list", "To combine lists"], answer: "To extract a portion of a sequence" },
  { question: "What is the output of 'print(\"a\" > \"b\")'?", options: ["True", "False", "None", "Error"], answer: "False" },
  { question: "Which keyword is used to return a value from a function?", options: ["give", "return", "back", "yield"], answer: "return" },
  { question: "What is a global variable?", options: ["A variable declared inside a function", "A variable that can be accessed anywhere", "A variable that never changes", "None of these"], answer: "A variable that can be accessed anywhere" },
  { question: "Which module is used to work with dates and times?", options: ["time", "datetime", "date", "calendar"], answer: "datetime" },
  { question: "What is the output of 'print(list(range(3)))'?", options: ["[1, 2, 3]", "[0, 1, 2]", "[0, 1, 2, 3]", "range(3)"], answer: "[0, 1, 2]" },
  { question: "Which data type is used to store multiple unique items?", options: ["List", "Set", "Tuple", "String"], answer: "Set" },
  { question: "What is 'Recursion'?", options: ["A loop that never ends", "A function calling itself", "A method to sort arrays", "A way to define classes"], answer: "A function calling itself" },
  { question: "Which of the following is the correct syntax for a list comprehension?", options: ["[x for x in list]", "{x for x in list}", "(x for x in list)", "None of these"], answer: "[x for x in list]" },
  { question: "What is the result of '\"apple\" == \"Apple\"'?", options: ["True", "False", "None", "Error"], answer: "False" },
  { question: "How do you add a comment that spans multiple lines?", options: ["Using # on every line", "Using triple quotes ''' '''", "Both A and B", "None of these"], answer: "Both A and B" },
  { question: "Which function is used to create a random integer?", options: ["random.random()", "random.randint()", "random.choice()", "random.seed()"], answer: "random.randint()" },
  { question: "What is the output of 'print(bool(\"\"))'?", options: ["True", "False", "None", "Error"], answer: "False" },
  { question: "What does the 'with' statement help with in file handling?", options: ["Writing faster", "Automatically closing the file", "Encrypting files", "Deleting files"], answer: "Automatically closing the file" },
  { question: "Which of the following is not a standard Python data type?", options: ["List", "Array", "Dictionary", "Tuple"], answer: "Array" },
  { question: "What is the result of 'print(2 + 3 * 4)'?", options: ["20", "14", "24", "None"], answer: "14" },
  { question: "Which method is used to join elements of a list into a string?", options: ["concat()", "join()", "merge()", "add()"], answer: "join()" },
  { question: "What is a 'module' in Python?", options: ["A type of function", "A file containing Python code", "A hardware component", "A loop type"], answer: "A file containing Python code" },
  { question: "What is the result of 'print(round(4.5))'?", options: ["4", "5", "4.0", "5.0"], answer: "4" },
  { question: "Which of the following is a Python IDE?", options: ["PyCharm", "IDLE", "Spyder", "All of the above"], answer: "All of the above" },
  { question: "What is the output of 'print(min([10, 20, 30]))'?", options: ["10", "30", "20", "None"], answer: "10" },
  { question: "What is an 'operator' in Python?", options: ["A type of loop", "Symbols used for operations", "A variable name", "A library name"], answer: "Symbols used for operations" },
  { question: "Which of the following represents a boolean value?", options: ["\"True\"", "true", "True", "1"], answer: "True" },
  { question: "What is the purpose of 'sys.argv'?", options: ["To get system time", "To get command-line arguments", "To sort lists", "To define functions"], answer: "To get command-line arguments" },
  { question: "Which function is used to find the maximum value in a list?", options: ["max()", "top()", "high()", "len()"], answer: "max()" },
  { question: "What is the result of 'print(\"hello\".capitalize())'?", options: ["Hello", "HELLO", "hello", "H"], answer: "Hello" },
  { question: "Which of the following is not a valid variable name?", options: ["_myvar", "my_var1", "1myvar", "myVar"], answer: "1myvar" },
  { question: "What is the output of 'print(sorted([3, 1, 2]))'?", options: ["[1, 2, 3]", "[3, 2, 1]", "[1, 3, 2]", "[3, 1, 2]"], answer: "[1, 2, 3]" },
  { question: "Which keyword is used to create a loop inside another loop?", options: ["double", "nest", "for", "None"], answer: "for" },
  { question: "What is the output of 'print(\"abc\".islower())'?", options: ["True", "False", "None", "Error"], answer: "True" },
];
