import React, { useState, useEffect, useCallback } from "react";

interface Question {
  question: string;
  options: string[];
  answer: string;
}

const questions: Question[] = [
  { question: "Who developed the OSI Model?", options: ["ISO (International Software Organization)", "ISO (International Standard Organization)", "ISO (Internet Standard Organization)", "ISO (International System Organization)"], answer: "ISO (International Standard Organization)" },
  { question: "Which instruction set architecture is used in Raspberry Pi?", options: ["ARM", "AVR", "MSP", "X86"], answer: "ARM" },
  { question: "What is the full form of WSN?", options: ["Wired Sensor Network", "Wide Sensor Network", "Wireless Sensor Network", "None of these"], answer: "Wireless Sensor Network" },
  { question: "Which layer is used in the transport layer to ensure data integrity?", options: ["Repetition codes", "Error correction codes", "Checksum", "Cyclic redundancy checks"], answer: "Checksum" },
  { question: "Which OSI layer converts digital bits into electrical, radio, or optical signals?", options: ["Network Layer", "Session Layer", "Physical Layer", "Application Layer"], answer: "Physical Layer" },
  { question: "In the network layer, data is transferred in the form of?", options: ["Bits", "Layers", "Bytes", "Packets"], answer: "Packets" },
  { question: "Which cloud computing service model virtualizes hardware in the cloud?", options: ["PaaS", "CaaS", "IaaS", "None of the mentioned"], answer: "IaaS" },
  { question: "In which control system the output does not affect the control action?", options: ["Closed Loop Control System", "Feedback Control System", "Open Loop Control System", "All of above"], answer: "Open Loop Control System" },
  { question: "What is a benefit of cloud computing services?", options: ["Anywhere access", "Fast", "Higher utilization", "All of the above"], answer: "All of the above" },
  { question: "Automatic control system is also known as?", options: ["Open Loop or Feedback Control System", "Open Loop or Non Feedback Control System", "Closed Loop or Feedback Control System", "None of these"], answer: "Closed Loop or Feedback Control System" },
  { question: "Which layer of the TCP/IP model performs the function of the top three layers of the OSI model?", options: ["Application Layer", "Transport Layer", "Session Layer", "Network Layer"], answer: "Application Layer" },
  { question: "How many layers are there in the OSI Model?", options: ["4 Layers", "5 Layers", "3 Layers", "7 Layers"], answer: "7 Layers" },
  { question: "Which layer provides security-based connections?", options: ["Session layer", "Application layer", "Network layer", "Transport layer"], answer: "Transport layer" },
  { question: "Which devices connect different types of devices through networks?", options: ["Fiber Optic network", "GPS, Wi-Fi, RFID", "Ethernet", "All of the above"], answer: "All of the above" },
  { question: "What does OSI stand for in OSI Model?", options: ["Open System Interconnection", "Operating System Interconnection", "Operating System Interaction", "Open System Internet"], answer: "Open System Interconnection" },
  { question: "What is the full form of PaaS?", options: ["Platform as a Survey", "People as a Service", "Platform as a Service", "Platform as a Survey"], answer: "Platform as a Service" },
  { question: "The initiation, maintenance, and termination of the physical connection in a network occur at which OSI layer?", options: ["Network Layer", "Application Layer", "Physical Layer", "Session Layer"], answer: "Physical Layer" },
  { question: "Which OSI layer is responsible for deciding the best route for data from source to destination?", options: ["Transport Layer", "Network Layer", "Application Layer", "Data Link Layer"], answer: "Network Layer" },
  { question: "Which Ethernet/LAN cable is used in Raspberry Pi?", options: ["cat6", "Cat5", "RJ45", "at5e"], answer: "RJ45" },
  { question: "Closed loop control system is also known as?", options: ["Feedback control system", "None of These", "Non-feedback control system", "Open Control System"], answer: "Feedback control system" },
  { question: "What is the LDR sensor used to measure?", options: ["Monitors Motion", "Monitors Light Intensity", "Monitors heartbeat", "Monitors air pressure"], answer: "Monitors Light Intensity" },
  { question: "How many pins are there in an LDR sensor?", options: ["4", "2", "5", "1"], answer: "2" },
  { question: "What is the maximum read range of an RFID module?", options: ["2 cm", "5 cm", "1 cm", "10 cm"], answer: "10 cm" },
  { question: "How many times does the setup function run in Arduino IDE?", options: ["None of the above", "2", "10", "1"], answer: "1" },
  { question: "What is the role of the cloud in smart grid architecture of IoT?", options: ["Collect data", "Manage data", "Security", "Store data"], answer: "Manage data" },
  { question: "Which of the following protocols is based on the REST architecture?", options: ["HTTP", "COAP", "Both A and B", "MQTT"], answer: "Both A and B" },
  { question: "Sensors can be?", options: ["Temperature sensors", "All of the above", "Light sensors", "Motion sensors"], answer: "All of the above" },
  { question: "The Raspbian OS used in Raspberry Pi is based on which OS?", options: ["Debian Linux", "RTOS", "Windows", "None of these above"], answer: "Debian Linux" },
  { question: "Actuators can be?", options: ["Display", "Sound", "All of the above", "Monitor"], answer: "All of the above" },
  { question: "The use of IoT architecture in production is referred to as what?", options: ["True", "False", "None of the above", "None of the mentioned"], answer: "True" },
  { question: "What are the different kinds of signals?", options: ["Mechanical, Thermal", "All of the above", "Chemical, Radiation", "Magnetic, Electric"], answer: "All of the above" },
  { question: "Sample and hold circuit is which type of circuit?", options: ["Digital device", "Analog device", "Neither analog nor digital", "Both analog and digital"], answer: "Analog device" },
  { question: "Which of the following is an example of a sensor?", options: ["Water Quality Sensor", "All of These", "Gas Sensor", "Moisture Sensor"], answer: "All of These" },
  { question: "To avoid aliasing, which type of filter is used?", options: ["Digital filter", "Anti-aliasing filter", "Aliasing filter", "Analog filter"], answer: "Anti-aliasing filter" },
  { question: "Which interface is used by the fingerprint sensor?", options: ["UART interface", "SPI interface", "COAP interface", "I2C interface"], answer: "UART interface" },
  { question: "Which of the following protocols is used by USART?", options: ["RS32", "4RS85", "RS232C", "All of the these"], answer: "All of the these" },
  { question: "Which sensors measure the heat energy produced by a source?", options: ["Temperature sensors", "Pressure sensors", "Humidity sensors", "Proximity sensors"], answer: "Temperature sensors" },
  { question: "Which of the following are included in actuators?", options: ["Valves, Switches", "Pumps, pistons", "Motors, gears", "All of the above"], answer: "All of the above" },
  { question: "Which type of touch sensor is used in cell phones?", options: ["Human sensor", "Capacitive touch sensor", "Follow sensor", "Resistive touch sensor"], answer: "Capacitive touch sensor" },
  { question: "What is a real example of a smart grid device in IoT?", options: ["Smart Meters", "Mobile phone", "Smart Speaker", "Television"], answer: "Smart Meters" },
  { question: "A microprocessor works using which type of digits?", options: ["1 / 1", "0 and 1", "0 / 0", "All of the above"], answer: "0 and 1" },
  { question: "What is the correct frequency for the Galileo Gen 2 board?", options: ["450 MHz", "300 MHz", "400 MHz", "250 MHz"], answer: "400 MHz" },
  { question: "What are the characteristics of RISC?", options: ["Pipelining", "Hardwired control", "Instructions executes in one clock cycle", "All of the above"], answer: "All of the above" },
  { question: "Which microcontroller is used in Arduino UNO prototyping board?", options: ["ATmega328p", "ATmega328m", "ATmega2560", "ATmega356p"], answer: "ATmega328p" },
  { question: "What is the full form of GPIO?", options: ["General Purpose Input Output Pins", "General Purpose Input Output Processor", "General Purpose Interested Old People", "General Purpose Inner Outer Propeller"], answer: "General Purpose Input Output Pins" },
  { question: "Which symbol is used for modulo calculation in Arduino?", options: ["%", "@", "$", "#"], answer: "%" },
  { question: "In which year was Arduino introduced?", options: ["1998", "2005", "2006", "2004"], answer: "2005" },
  { question: "Electricity sensors convert light rays into electrical signals.", options: ["False", "May be", "True", "Can't say"], answer: "False" },
  { question: "_______ actuators use pressurized oil that is incompressible?", options: ["Hydraulic", "Pneumatic", "Both (a) and (b)", "None of these"], answer: "Hydraulic" },
  { question: "A capacitor blocks AC and allows DC to pass through.", options: ["False", "Cant say", "True", "May be"], answer: "True" },
