import React, { useState, useEffect, useCallback } from "react";

interface Question {
  question: string;
  options: string[];
  answer: string;
}

const questions: Question[] = [
  { question: "Who developed the OSI Model?", options: ["ISO (International Software Organization)", "ISO (International Standard Organization)", "ISO (Internet Standard Organization)", "ISO (International System Organization)"], answer: "ISO (International Standard Organization)" },
  { question: "Which instruction set architecture is used in Raspberry Pi?", options: ["ARM", "AVR", "MSP", "X86"], answer: "ARM" },
  { question: "What is the full form of WSN?", options: ["Wired Sensor Network", "Wide Sensor Network", "Wireless Sensor Network", "None of these"], answer: "Wireless Sensor Network" },
  { question: "Which layer is used in the transport layer to ensure data integrity?", options: ["Repetition codes", "Error correction codes", "Checksum", "Cyclic redundancy checks"], answer: "Checksum" },
  { question: "Which OSI layer converts digital bits into electrical, radio, or optical signals?", options: ["Network Layer", "Session Layer", "Physical Layer", "Application Layer"], answer: "Physical Layer" },
  { question: "In the network layer, data is transferred in the form of?", options: ["Bits", "Layers", "Bytes", "Packets"], answer: "Packets" },
  { question: "Which cloud computing service model virtualizes hardware in the cloud?", options: ["PaaS", "CaaS", "IaaS", "None of the mentioned"], answer: "IaaS" },
  { question: "In which control system the output does not affect the control action?", options: ["Closed Loop Control System", "Feedback Control System", "Open Loop Control System", "All of above"], answer: "Open Loop Control System" },
  { question: "What is a benefit of cloud computing services?", options: ["Anywhere access", "Fast", "Higher utilization", "All of the above"], answer: "All of the above" },
  { question: "Automatic control system is also known as?", options: ["Open Loop or Feedback Control System", "Open Loop or Non Feedback Control System", "Closed Loop or Feedback Control System", "None of these"], answer: "Closed Loop or Feedback Control System" },
  { question: "Which layer of the TCP/IP model performs the function of the top three layers of the OSI model?", options: ["Application Layer", "Transport Layer", "Session Layer", "Network Layer"], answer: "Application Layer" },
  { question: "How many layers are there in the OSI Model?", options: ["4 Layers", "5 Layers", "3 Layers", "7 Layers"], answer: "7 Layers" },
  { question: "Which layer provides security-based connections?", options: ["Session layer", "Application layer", "Network layer", "Transport layer"], answer: "Transport layer" },
  { question: "Which devices connect different types of devices through networks?", options: ["Fiber Optic network", "GPS, Wi-Fi, RFID", "Ethernet", "All of the above"], answer: "All of the above" },
  { question: "What does OSI stand for in OSI Model?", options: ["Open System Interconnection", "Operating System Interconnection", "Operating System Interaction", "Open System Internet"], answer: "Open System Interconnection" },
  { question: "What is the full form of PaaS?", options: ["Platform as a Survey", "People as a Service", "Platform as a Service", "Platform as a Survey"], answer: "Platform as a Service" },
  { question: "The initiation, maintenance, and termination of the physical connection in a network occur at which OSI layer?", options: ["Network Layer", "Application Layer", "Physical Layer", "Session Layer"], answer: "Physical Layer" },
  { question: "Which OSI layer is responsible for deciding the best route for data from source to destination?", options: ["Transport Layer", "Network Layer", "Application Layer", "Data Link Layer"], answer: "Network Layer" },
  { question: "Which Ethernet/LAN cable is used in Raspberry Pi?", options: ["cat6", "Cat5", "RJ45", "at5e"], answer: "RJ45" },
  { question: "Closed loop control system is also known as?", options: ["Feedback control system", "None of These", "Non-feedback control system", "Open Control System"], answer: "Feedback control system" },
  { question: "What is the LDR sensor used to measure?", options: ["Monitors Motion", "Monitors Light Intensity", "Monitors heartbeat", "Monitors air pressure"], answer: "Monitors Light Intensity" },
  { question: "How many pins are there in an LDR sensor?", options: ["4", "2", "5", "1"], answer: "2" },
  { question: "What is the maximum read range of an RFID module?", options: ["2 cm", "5 cm", "1 cm", "10 cm"], answer: "10 cm" },
  { question: "How many times does the setup function run in Arduino IDE?", options: ["None of the above", "2", "10", "1"], answer: "1" },
  { question: "What is the role of the cloud in smart grid architecture of IoT?", options: ["Collect data", "Manage data", "Security", "Store data"], answer: "Manage data" },
  { question: "Which of the following protocols is based on the REST architecture?", options: ["HTTP", "COAP", "Both A and B", "MQTT"], answer: "Both A and B" },
  { question: "Sensors can be?", options: ["Temperature sensors", "All of the above", "Light sensors", "Motion sensors"], answer: "All of the above" },
  { question: "The Raspbian OS used in Raspberry Pi is based on which OS?", options: ["Debian Linux", "RTOS", "Windows", "None of these above"], answer: "Debian Linux" },
  { question: "Actuators can be?", options: ["Display", "Sound", "All of the above", "Monitor"], answer: "All of the above" },
  { question: "The use of IoT architecture in production is referred to as what?", options: ["True", "False", "None of the above", "None of the mentioned"], answer: "True" },
  { question: "What are the different kinds of signals?", options: ["Mechanical, Thermal", "All of the above", "Chemical, Radiation", "Magnetic, Electric"], answer: "All of the above" },
  { question: "Sample and hold circuit is which type of circuit?", options: ["Digital device", "Analog device", "Neither analog nor digital", "Both analog and digital"], answer: "Analog device" },
  { question: "Which of the following is an example of a sensor?", options: ["Water Quality Sensor", "All of These", "Gas Sensor", "Moisture Sensor"], answer: "All of These" },
  { question: "To avoid aliasing, which type of filter is used?", options: ["Digital filter", "Anti-aliasing filter", "Aliasing filter", "Analog filter"], answer: "Anti-aliasing filter" },
  { question: "Which interface is used by the fingerprint sensor?", options: ["UART interface", "SPI interface", "COAP interface", "I2C interface"], answer: "UART interface" },
  { question: "Which of the following protocols is used by USART?", options: ["RS32", "4RS85", "RS232C", "All of the these"], answer: "All of the these" },
  { question: "Which sensors measure the heat energy produced by a source?", options: ["Temperature sensors", "Pressure sensors", "Humidity sensors", "Proximity sensors"], answer: "Temperature sensors" },
  { question: "Which of the following are included in actuators?", options: ["Valves, Switches", "Pumps, pistons", "Motors, gears", "All of the above"], answer: "All of the above" },
  { question: "Which type of touch sensor is used in cell phones?", options: ["Human sensor", "Capacitive touch sensor", "Follow sensor", "Resistive touch sensor"], answer: "Capacitive touch sensor" },
  { question: "What is a real example of a smart grid device in IoT?", options: ["Smart Meters", "Mobile phone", "Smart Speaker", "Television"], answer: "Smart Meters" },
  { question: "A microprocessor works using which type of digits?", options: ["1 / 1", "0 and 1", "0 / 0", "All of the above"], answer: "0 and 1" },
  { question: "What is the correct frequency for the Galileo Gen 2 board?", options: ["450 MHz", "300 MHz", "400 MHz", "250 MHz"], answer: "400 MHz" },
  { question: "What are the characteristics of RISC?", options: ["Pipelining", "Hardwired control", "Instructions executes in one clock cycle", "All of the above"], answer: "All of the above" },
  { question: "Which microcontroller is used in Arduino UNO prototyping board?", options: ["ATmega328p", "ATmega328m", "ATmega2560", "ATmega356p"], answer: "ATmega328p" },
  { question: "What is the full form of GPIO?", options: ["General Purpose Input Output Pins", "General Purpose Input Output Processor", "General Purpose Interested Old People", "General Purpose Inner Outer Propeller"], answer: "General Purpose Input Output Pins" },
  { question: "Which symbol is used for modulo calculation in Arduino?", options: ["%", "@", "$", "#"], answer: "%" },
  { question: "In which year was Arduino introduced?", options: ["1998", "2005", "2006", "2004"], answer: "2005" },
  { question: "Electricity sensors convert light rays into electrical signals.", options: ["False", "May be", "True", "Can't say"], answer: "False" },
  { question: "_______ actuators use pressurized oil that is incompressible?", options: ["Hydraulic", "Pneumatic", "Both (a) and (b)", "None of these"], answer: "Hydraulic" },
  { question: "A capacitor blocks AC and allows DC to pass through.", options: ["False", "Cant say", "True", "May be"], answer: "True" },
  { question: "What is the full form of SISO?", options: ["Single Input Single Output", "Single Input Some Output", "Some Input Single Output", "Some Input Some Output"], answer: "Single Input Single Output" },
  { question: "8051 Microcontroller is used in which of the following fields?", options: ["Medical Equipment", "Defense System", "Aeronautical and space", "All of the above"], answer: "All of the above" },
  { question: "What is the full form of RISC (Q.53)?", options: ["Reduce Instruction Set Computer", "ROM Instruction Set Computer", "Retrive Instruction Signal Computer", "Retrive Instruction Set Computer"], answer: "Reduce Instruction Set Computer" },
  { question: "Which touchscreen is made of a glass overlay?", options: ["Resistive Touchscreen", "APR", "SAW", "Capacitive Touchscreen"], answer: "Resistive Touchscreen" },
  { question: "_______ sensors provide digital outputs that can be directly connected to a digital controller.", options: ["Analog", "Digital", "None of these", "Both (a) and (b)"], answer: "Digital" },
  { question: "Which of the following is not included in an actuator?", options: ["Piston", "Gear", "Controller", "Motors"], answer: "Controller" },
  { question: "What is the full form of AVR?", options: ["Analog Virtual Reduction", "Alf-Egil Bogen Vegard Wollan Risc", "Analog Vegard Risc", "Analog Vegard Reduction"], answer: "Alf-Egil Bogen Vegard Wollan Risc" },
  { question: "Is a sensor an output device?", options: ["False", "May be", "Cant say", "True"], answer: "False" },
  { question: "What is the full form of PIC?", options: ["Programmable Integrated Circuit", "Program Interface Controller", "Programmable Interface Controller", "Program Integrated Circuit"], answer: "Programmable Interface Controller" },
  { question: "Which type of sensor is used in mobile phones?", options: ["Capacitive touch sensor", "Temperature sensor", "Weight sensor", "Humidity sensor"], answer: "Capacitive touch sensor" },
  { question: "Which symbol is used to calculate modulo in Arduino (Q.61)?", options: ["% (percentage)", "# (hash)", "$ (dollar)", "! (not equal)"], answer: "% (percentage)" },
  { question: "What is the meaning of 'p' in Atmega328p?", options: ["Picopower", "Process", "Pins", "Pixels"], answer: "Picopower" },
  { question: "Global Sensor Network is built for what purpose?", options: ["Reducing cost and time for development", "Increasing cost and decreasing time for development", "Reducing cost and increasing time for development", "Increasing cost and increasing time for development"], answer: "Reducing cost and time for development" },
  { question: "Does Arduino IDE provide an environment?", options: ["True", "May be True or False", "None of the Above", "False"], answer: "True" },
  { question: "What is ESP8266?", options: ["WIFI module", "Board", "USB cable", "Sensor"], answer: "WIFI module" },
  { question: "Which device consists of two different metals connected at two points?", options: ["Thermocouple", "Thermistor", "Semiconductor based sensor", "Resistance Thermometer"], answer: "Thermocouple" },
  { question: "The smallest difference that a sensor can detect is called?", options: ["Resolution", "Accuracy", "Scale", "Precision"], answer: "Resolution" },
  { question: "How many types of failures are there in capacitive type humidity sensors?", options: ["3", "2", "6", "4"], answer: "4" },
  { question: "When the microcontroller performs arithmetic operations, which register's flag bits are affected?", options: ["PSW", "DPTR", "SP", "PC"], answer: "PSW" },
  { question: "How many flags are there in the 8085 Microprocessor?", options: ["5", "15", "12", "9"], answer: "5" },
  { question: "What is DHT11?", options: ["Humidity Sensor", "Microprocessor", "Switching Device", "Motion Sensor"], answer: "Humidity Sensor" },
  { question: "Which of the following is not an actuator?", options: ["Shutter doors", "DC Motor", "Relay", "Stepper Motor"], answer: "Shutter doors" },
  { question: "Is Microcontroller the brain of IoT devices?", options: ["True", "May be True or False", "False", "None of the Above"], answer: "True" },
  { question: "Which of the following is false about microcontrollers?", options: ["Its power consumption is high because it has to control the entire system.", "Microcontrollers are used to execute a single task within an application.", "It is built with CMOS technology.", "It consists of CPU, RAM, ROM, I/O ports."], answer: "Its power consumption is high because it has to control the entire system." },
  { question: "What is the main function of a sensor?", options: ["Track & transfer data to processor", "Activate response", "Separate physical parameters", "Move a robotic arm"], answer: "Track & transfer data to processor" },
  { question: "Sensor generates an output signal based on what?", options: ["Input", "None of These", "Physical", "Data"], answer: "Physical" },
  { question: "Which of the following is an example of a 16-bit microcontroller?", options: ["8096 Microcontroller", "8031 Microcontroller", "None of the above", "8051 Microcontroller"], answer: "8096 Microcontroller" },
  { question: "How many pins are there in 8085 Microprocessor?", options: ["40", "35", "45", "30"], answer: "40" },
  { question: "What is used in IoT devices to capture data from the physical world?", options: ["Sensors", "Microcontrollers", "Actuators", "Microprocessors"], answer: "Sensors" },
  { question: "What is the use of the IR sensor?", options: ["Object Detection", "Humidity Detection", "Image Processing", "GPS"], answer: "Object Detection" },
  { question: "Arduino Uno is the most popular type of Arduino board?", options: ["Cant say", "True", "False", "May be"], answer: "True" },
  { question: "Almost all statements written in the Arduino language must end with?", options: ["Semicolon (;)", "Full stop (.)", "Colon (:)", "Comma (,)"], answer: "Semicolon (;)" },
  { question: "To easily interface add-on modules with Arduino, we can use?", options: ["Arduino shields", "Other high-end Arduino boards", "General PCB", "Connectivity circuit boards"], answer: "Arduino shields" },
  { question: "Secure digital card application uses which of the following protocols?", options: ["MQTT", "SPI", "HTTPS", "XMPP"], answer: "SPI" },
  { question: "All code in an Arduino sketch is processed from Arduino in which order?", options: ["Top to bottom", "Any order", "Bottom to top", "None of these"], answer: "Top to bottom" },
  { question: "The following database is recommended for unstructured data for IoT applications?", options: ["Mongo DB", "None of the above", "Microsoft SQL", "Postgres SQL"], answer: "Mongo DB" },
  { question: "Arduino is introduced by _______?", options: ["Massimo Banzi", "Dennis Ritchie", "James Gosling", "Tim Berners-Lee"], answer: "Massimo Banzi" },
  { question: "Which symbol is used in Arduino to calculate modulo?", options: ["%", "$", "!", "#"], answer: "%" },
  { question: "How many digital pins does a UNO board have?", options: ["14", "16", "10", "8"], answer: "14" },
  { question: "Which is the first board to use a microcontroller with built-in USB?", options: ["Leonardo", "UNO", "RedBoard", "LilyPad"], answer: "Leonardo" },
  { question: "How many types of Arduinos do we have?", options: ["8", "6", "14", "1"], answer: "8" },
  { question: "Which language is the Arduino IDE written in?", options: ["JavaScript", "C++", "C", "Both A & D"], answer: "Both A & D" },
  { question: "Which microcontroller is used in the Arduino UNO prototyping board?", options: ["ATmega328p", "ATmega2560", "ATmega328m", "None"], answer: "ATmega328p" },
  { question: "Which of the following is not an application of IoT?", options: ["Arduino", "Wearables", "Smart Grid", "Smart City"], answer: "Arduino" },
  { question: "The setup() defines?", options: ["Pin functionality using the pinMode function", "Initialize classes and variables", "Initial state of pins", "All of the above"], answer: "All of the above" },
  { question: "Some of the compile errors are?", options: ["Missing variable initialization", "Misspellings & wrong capitalizations", "Missing semicolons or parentheses", "All of the above"], answer: "All of the above" },
  { question: "Traditional operating systems such as Windows and iOS are made for IoT applications?", options: ["True", "False", "Both", "None"], answer: "False" },
  { question: "The SPI pins are?", options: ["pins 10 (SS), 11", "Both (a) and (b)", "None of these", "12 (MISO), 13 (SCK) (MOSI)"], answer: "Both (a) and (b)" },
  { question: "Which of the following statements are true about serial communication?", options: ["Can be either setup() and loop ()", "Only setup ()", "Only loop()", "setup() loop()"], answer: "Can be either setup() and loop ()" },
  { question: "What are the advantages of Arduino?", options: ["Easy to learn", "Many third-party libraries", "Huge community", "All of the above"], answer: "All of the above" },
];
